#define USER_INTC_IRQ_FIT_MASK 0x01
#define USER_INTC_IRQ_BUTTONS_MASK 0x02
#define USER_INTC_IRQ_SWITCHES_MASK 0x04
#define USER_INTC_IRQ_PIT_MASK 0x08

#define USER_INTC_IRQ_FIT_IRQ 0x01
#define USER_INTC_IRQ_BUTTONS_IRQ 0x02
#define USER_INTC_IRQ_SWITCHES_IRQ 0x04
#define USER_INTC_IRQ_PIT_IRQ 0x08

#define USER_LEDS_UIO_FILE "/dev/uio0"
#define USER_BUTTONS_UIO_FILE "/dev/uio1"
#define USER_SWITCHES_UIO_FILE "/dev/uio2"
#define USER_RGBLEDS_UIO_FILE "/dev/uio3"
#define USER_INTC_UIO_FILE "/dev/uio4"
